- name: Manage Docker containers
  hosts: all
  user: ubuntus
  gather_facts: no
  vars_files:
    - vars/docker_vars.yml
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present
      become: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "{{ container_port }}:{{ container_port }}"
