apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects: 
  - secretName: revhire/mysql
    type: Opaque
    data:
    - objectName: DB_USERNAME
      key: username
    - objectName: DB_PASSWORD
      key: password
    - objectName: DB_PORT
      key: host
    - objectName: DB_URL
      key: port
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:020134821626:secret:revhire/mysql-Cicxml"
        jmesPath: 
            - path: username
              objectAlias: DB_USERNAME
            - path: password
              objectAlias: DB_PASSWORD
            - path: host
              objectAlias: DB_URL
            - path: port
              objectAlias: DB_PORT
              