apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: demo-app
  name: example-rule
spec:
  groups:
  - name: example-rule
    rules:
    - alert: example-alert
      annotations:
        description: user traffic is high
        summary: user traffic is high on {{ $labels.pod }}
      expr: |
        (users_c_total+home_c_created+jobs_c_total+kill_c_total) > 10
      for: 2s
      labels:
        severity: warning
