apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-user
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revhire-user
  template:
    metadata:
      labels:
        app : revhire-user
    spec:
      containers:
        - name: revhire-user
          image: public.ecr.aws/a6p3b4m6/revhire-user-service:latest
          env:
          - name : DB_URL
            value: revhire-db.cnlwgkdvldnm.us-east-1.rds.amazonaws.com
          - name : DB_USERNAME
            value: revhire
          - name : DB_PASSWORD
            value: revhire4444
          - name: DB_PORT
            value: "3306"          
---
apiVersion: v1
kind: Service
metadata:
  name: revhire-user-service
  labels:
    app: revhire-user
spec:
  selector:
    app: revhire-user
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
  type: LoadBalancer
---

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d088cc21dd17a45a