---
apiVersion: v1
kind: Service
metadata:
  name: revhire-job-service
  labels:
    app: revhire-job
spec:
  selector:
    app: revhire-job
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  type: ClusterIP