---
apiVersion: v1
kind: Service
metadata:
  name: revhire-user-service
  labels:
    app: revhire-user
spec:
  selector:
    app: revhire-user
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
  type: ClusterIP